version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.8.16-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - ./.db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  java:
    image: leothenardo/asapcard-java-consumer:latest
    container_name: java
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/db
      - RABBITMQ_HOST=rabbitmq
    restart: always
#  golang:
#    image: leo00ff/asapcard-golang-producer:latest
#    container_name: golang
#    volumes:
#      - pathtolisten:/input
#      - pathtolisten:/conciliation
#    environment:
#      - RABBITMQ_HOST=rabbitmq
#    restart: always